# gradle:
#org.gradle.caching=false
#org.gradle.daemon=false
#org.gradle.parallel=true
#org.gradle.jvmargs=-Xss10240k -Dfile.encoding=utf-8
#org.gradle.jvmargs=-Xss10240k
org.gradle.jvmargs=-Duser.language=en -Duser.country=US -Dfile.encoding=UTF-8

# installed JDKs
#org.gradle.java.installations.paths=\
#  D:\\opt\\JDK\\azul-1.8.0_462,\
#  D:\\opt\\JDK\\azul-17.0.16,\
#  D:\\opt\\JDK\\openjdk-25,

# versions
projectVersion=0.0.0
# kotlin
kotlinVersion=2.2.20
# jacoco
jacocoToolVersion=0.8.14
# jmh
jmhPluginVersion=0.7.3

# repos
xGradlePluginRepo="https://maven.aliyun.com/repository/gradle-plugin"
# xMavenRepo="https://maven.aliyun.com/repository/central"
xMavenRepo="https://maven.aliyun.com/repository/public"

# plugin logger
pluginLogLevel=INFO